### ISSUE TITLE
Does not respect gitignore

### ISSUE THREAD

**Issue by nipunarora** [AshyIsMe/fzf-spacemacs-layer#1]
This is super useful, but for some reason this layer does not respect gitignore. Do you know why that would be the case?

**Comment by AshyIsMe** [comment]
Unfortunately I've gone back to vim for the most part.  You will have to dig in to the upstream fzf.el library:

Edit the library included here: https://github.com/AshyIsMe/fzf-spacemacs-layer/blob/master/packages.el#L25-L27

Upstream is here:
https://github.com/seenaburns/fzf.el

**Comment by alkhaldieid** [comment]
I know this is too late, but for fzf to respect .gitignore you need to modify the FZF_DEFAULT_COMMAND variable to some command that respect .gitignore. 
In my case I added "export FZF_DEFAULT_COMMAND='ag -p ~/.gitignore -g'" to my shell.
